version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@realestatefnft-database-1:27017/
    depends_on: 
      - database
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    depends_on: 
      - backend
      - database
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - rnft:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  rnft:
